version: "3"
services:
  react-app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=julien-prod
    ports:
      - "8080:8080"
    # env_file:
    #   - ./.env